global using Xunit;
global using Moq;
global using FluentAssertions;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.Extensions.Logging;
global using CleanArchRepoTemplate.API.Controllers;
global using CleanArchRepoTemplate.Core.Entities;
global using CleanArchRepoTemplate.Core.Interfaces;
global using CleanArchRepoTemplate.Fixtures;
