name: Build Test And Deploy

on:
  - pull_request
  - push

jobs:
  dotnet_build_and_test:
    name: Build And Test .NET 6 Projects
    runs-on: ubuntu-latest

    steps:
    - name: Checkout To Branch
      uses: actions/checkout@v3

    - name: Setup .NET 6.0.x
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Restore .NET Dependencies
      run: dotnet restore

    - name: Build .NET
      run: dotnet build --no-restore

    - name: Run .NET Tests
      run: dotnet test --no-restore --verbosity normal

  nodejs_build_and_test:
    needs: dotnet_build_and_test
    name: Build And Test Node.js 16.x Projects
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/client-app/

    steps:
    - name: Checkout To Branch
      uses: actions/checkout@v3

    - name: Setup Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x

    - name: Install Node.js
      run: npm ci

    - name: Build Node.js
      run: npm run build

  deploy-to-nuget:
    needs: nodejs_build_and-_est
    name: Publish Template to NuGet
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout To Branch
      uses: actions/checkout@v3

    - name: Setup NuGet
      uses: nuget/setup-nuget@v1
      with:
        nuget-version: '5.x'

    - name: Package The Template
      run: nuget pack CleanArchRepoTemplate.nuspec -NoDefaultExcludes

    - name: Publish Template To NuGet
      run: nuget push Gagibran.CleanArchRepo.Template.*.nupkg -Source https://api.nuget.org/v3/index.json ${{ secrets.NUGET_API_KEY }} -SkipDuplicate
