name: Publish Template to NuGet

on:
  workflow_run:
    workflows: [Clean Architecture Build]
    types: [completed]

jobs:
  publish-on-build-success:
    name: Publish Template to NuGet
    runs-on: ubuntu-latest
    if: ${{ (github.event.workflow_run.conclusion == 'success') && (github.ref == 'refs/heads/main') }}

    steps:
      - name: Checkout To Branch
        uses: actions/checkout@v3

      - name: Get All Changed Files
        id: changed-files
        uses: tj-actions/changed-files@v23.1

      - name: Setup NuGet
        uses: nuget/setup-nuget@v1
        with:
          nuget-version: '5.x'

      - name: Package The Template
        run: nuget pack CleanArchRepoTemplate.nuspec -NoDefaultExcludes

      - name: Publish To nuget.org
        run: |
            for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
              if [[ $file == CleanArchRepoTemplate.nuspec ]]; then
                echo "$file changed. Publishing new version to nuget.org..."
                nuget push Gagibran.CleanArchRepo.Template.*.nupkg -src https://api.nuget.org/v3/index.json ${{ secrets.NUGET_API_KEY }}
              fi
            done