name: Publish Template to NuGet Job

on:
  push:
    branches: [ main ]
    paths:
      - 'CleanArchRepoTemplate.nuspec'

jobs:
  publish:
    name: Publish Template to NuGet
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: nuget/setup-nuget@v1
        with:
          nuget-version: '5.x'
          
      - name: PackageTemplate
        run: nuget pack CleanArchRepoTemplate.nuspec -NoDefaultExcludes

      - name: Publish to nuget.org
        run: nuget push Gagibran.CleanArchRepo.Template.*.nupkg -src https://api.nuget.org/v3/index.json ${{secrets.NUGET_API_KEY}}